version: "3.7"
services:
  helloworld:
    image: strm/helloworld-http
    restart: unless-stopped
    networks:
      rp:
        aliases:
          - helloapp
          - helloworld

networks:
  rp:
    external: true
