version: "3.7"
services:
  helloworld:
    image: strm/helloworld-http
    restart: unless-stopped
    hostname: helloworld
    deploy:
      replicas: 1
    networks:
     -  rp

networks:
  rp:
    external: true
