version: "3.7"
services:
  helloworld:
    image: strm/helloworld-http
    restart: unless-stopped
    deploy:
      replicas: 1
      aliases:
           - helloworld
    networks:
     -  rp

networks:
  rp:
    external: true
